### PR TITLE
Fix: Watch Pattern

### PR DESCRIPTION
**Pull request by gpedro**

### CODE REVIEW

**Comment by gpedro** [comment]
#109

**Comment by zenorocha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by zenorocha** [comment]
Hey @gpedro, I tried changing a value in `src/layout/default.html` and changes were not updated.

**Comment by gpedro** [comment]
@zenorocha 
[](http://i.imgur.com/7o099BE.png)

**Comment by gpedro** [comment]
it appears that changed, but we need a trigger to rebuild.

**Comment by obetomuniz** [comment]
@gpedro @zenorocha The link below show another implementation using **path module**  

https://github.com/braziljs/conf-boilerplate/blob/migration/docpad2metalsmith/metalsmith.js

**Comment by zenorocha** [comment]
I noticed that too @gpedro, could you send a fix?

**Comment by gpedro** [comment]
path.join LGTM. i'm trying understand how to trigger build on watch

**Comment by gpedro** [comment]
well, the problem is caused by 
> metalsmith.source('src/documents')

the rebuilder is working, but the source path fucks my life. If I change the layout/default and save, it creates the layouts folder in the root directory.
this happens with both branches `migration/docpad2metalsmith` as `metalsmith`

cc @zenorocha @obetomuniz

**Comment by zenorocha** [comment]
I see... well, we could try another solution such as [metalsmith-simplewatch](https://github.com/christophercliff/metalsmith-simplewatch).

That way we don't need to create another build step to filter what is generated and what isn't.

**Comment by zenorocha** [comment]
Could you check it out @gpedro?

**Comment by gpedro** [comment]
I will test this.

**Comment by gpedro** [comment]
@zenorocha, @obetomuniz 
Gulp LGTM
https://github.com/gpedro/conf-boilerplate/commits/feature/metalsmith-gulp

**Comment by zenorocha** [comment]
I love gulp but introducing another build tool doesn't look good to me.

**Comment by zenorocha** [comment]
Maybe a standalone solution like [simple-recursive-watch](https://www.npmjs.com/package/simple-recursive-watch) may work.

**Comment by gpedro** [comment]
simple-recursive-watch works! but the metalsmith does not work. When he will rebuild, rather than loading the file name, it loads the content in the name, like, WTF?

**Comment by zenorocha** [comment]
wait, what? hahaha

can you send your code so we can take a look?

**Comment by gpedro** [comment]
@zenorocha https://github.com/gpedro/conf-boilerplate/tree/fix/metalsmith-watch

**Comment by zenorocha** [comment]
Tried several stuff here and still couldn't make it work. @obetomuniz, could you take a look?

**Comment by gpedro** [comment]
@zenorocha, I will create an issue at segmentio/metalsmith reporting that.

**Comment by diogomoretti** [comment]
Any solution to the watch? The [metalsmith watch](https://github.com/FWeinb/metalsmith-watch) it is now in version 1.0.1. Or we will use [gulp method](https://github.com/gpedro/conf-boilerplate/commits/feature/metalsmith-gulp)?

**Comment by gpedro** [comment]
@diogomoretti i will try with the 1.0.1

**Comment by diogomoretti** [comment]
The same error for me in your gif :/

**Comment by gpedro** [comment]
why we choose metalsmith?

**Comment by zenorocha** [comment]
Problem fixed.

**Comment by zenorocha** [comment]
I chose metalsmith after evaluating all the other JavaScript-based static generators.

**Pull request closed without merging**
